### ISSUE TITLE
Failed prop type on loading the front-end (localhost:3000)

### ISSUE THREAD

**Issue by davidverity** [sanity-io/sanity-template-nextjs-landing-pages#63]
Hello, I started using this repo/template and when I try to access the front-end after running npm install and npm run dev in the root folder, I am receiving those warnings, even without changing anything in the code:

`next-dev.js?3515:32 Warning: Failed prop type: Invalid prop `navItems[0].slug` of type `object` supplied to `Header`, expected an array.
    at Header (webpack-internal:///./components/Header.js:130:9)
    at WithRouterWrapper (webpack-internal:///./node_modules/next/dist/client/with-router.js:18:34)
    at div
    at Layout (webpack-internal:///./components/Layout.js:22:24)
    at LandingPage (webpack-internal:///./pages/[[...slug]].js:29:24)
    at App (webpack-internal:///./pages/_app.js:172:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:359:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:793:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:915:27)
window.console.error @ next-dev.js?3515:32
printWarning @ react.development.js?1b7e:220
error @ react.development.js?1b7e:196
checkPropTypes @ react.development.js?1b7e:1935
validatePropTypes @ react.development.js?1b7e:2136
createElementWithValidation @ react.development.js?1b7e:2240
WithRouterWrapper @ with-router.js?ac7c:15
renderWithHooks @ react-dom.development.js?ac89:14985
mountIndeterminateComponent @ react-dom.development.js?ac89:17811
beginWork @ react-dom.development.js?ac89:19049
beginWork$1 @ react-dom.development.js?ac89:23940
performUnitOfWork @ react-dom.development.js?ac89:22776
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21881
updateContainer @ react-dom.development.js?ac89:25482
eval @ react-dom.development.js?ac89:26021
unbatchedUpdates @ react-dom.development.js?ac89:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
hydrate @ react-dom.development.js?ac89:26086
renderReactElement @ index.js?46cb:518
doRender @ index.js?46cb:830
_callee$ @ index.js?46cb:414
tryCatch @ runtime.js?ecd4:45
invoke @ runtime.js?ecd4:274
prototype.<computed> @ runtime.js?ecd4:97
asyncGeneratorStep @ index.js?46cb:31
_next @ index.js?46cb:49
eval @ index.js?46cb:54
eval @ index.js?46cb:46
_render @ index.js?46cb:433
render @ index.js?46cb:436
eval @ next-dev.js?3515:86
eval @ fouc.js?0087:12
requestAnimationFrame (async)
displayContent @ fouc.js?0087:7
eval @ next-dev.js?3515:85
Promise.then (async)
eval @ next-dev.js?3515:48
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1651272554552:148
options.factory @ webpack.js?ts=1651272554552:633
__webpack_require__ @ webpack.js?ts=1651272554552:37
__webpack_exec__ @ main.js?ts=1651272554552:722
(anonymous) @ main.js?ts=1651272554552:723
webpackJsonpCallback @ webpack.js?ts=1651272554552:1179
(anonymous) @ main.js?ts=1651272554552:9
Show 5 more frames
next-dev.js?3515:32 Warning: Failed prop type: Invalid prop `navItems[0].slug` of type `object` supplied to `Footer`, expected an array.
    at Footer (webpack-internal:///./components/Footer.js:27:26)
    at WithRouterWrapper (webpack-internal:///./node_modules/next/dist/client/with-router.js:18:34)
    at div
    at Layout (webpack-internal:///./components/Layout.js:22:24)
    at LandingPage (webpack-internal:///./pages/[[...slug]].js:29:24)
    at App (webpack-internal:///./pages/_app.js:172:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:359:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:793:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:915:27)`
    
Did anybody had the same issue?
Thanks.

**Comment by LinnJS** [comment]
This is an issue I got as well I can open up a tinny little PR to fix it. Looks like on the Sanity side a prop was changes from a array to an object.
